@baseUrl = http://localhost:3000
@bookId = 6758ba293595bb21f86b07ed

### Pesquisa todos os livros
GET {{baseUrl}}/api/books?page=1

### Pesquisa um livro específico
GET {{baseUrl}}/api/books/{{bookId}}

### Cria um novo livro
POST {{baseUrl}}/api/books
Content-Type: application/json

{
    "title": "Crime e Castigo",
    "description": "Crime e Castigo é um romance do escritor Fiódor Dostoiévski",
    "publishDate": "1866-01-05",
    "pageCount": 592
}

### Altera o livro com id={{bookId}}
PUT {{baseUrl}}/api/books/{{bookId}}
Content-Type: application/json

{
    "title": "A Metamorfose",
    "description": "A Metamorfose é uma novela escrita por Franz Kafka",
    "publishDate": "1915-12-10",
    "pageCount": 96
}

### Exclui um livro específico
DELETE {{baseUrl}}/api/books/{{bookId}}
